name: main
on: [push, pull_request]
jobs:
  go:
    name: go
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: go build
        run: go build -v ./...
      - name: go test
        run: go test -v ./...
      - name: go vet
        run: go vet ./...
